Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -1,4 +1,4 @@
-name: C++ Build and Run
+name: C++ Build and Check
 
 on:
   push:
@@ -17,7 +17,11 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Build with make
-      run: make
-
-    - name: Run Executable
-      run: ./main
+      run: |
+        if make; then
+          echo "Build successful"
+          exit 0
+        else
+          echo "Build failed"
+          exit 1
+        fi
